In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [33]:
# membaca data .csv untuk dilakukan preparation
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Genetic_Algorithm/df_minmax.csv') 
display(df.describe())

,P0,Q0,V0,RHO,T0,RE,ALFA,BETA,CL,CD,CM25,CYAW,CROLL,CY
count,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000
mean,0.534304,0.465120,0.512478,0.439759,0.490913,0.403119,0.517440,0.499689,0.492656,0.384086,0.511921,0.503364,0.505437,0.508441
std,0.254442,0.191464,0.167923,0.224015,0.206150,0.201372,0.279392,0.180136,0.275992,0.252957,0.291318,0.304580,0.294464,0.296713
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.395018,0.320988,0.375000,0.214286,0.350205,0.242424,0.332065,0.500000,0.248125,0.180980,0.375000,0.375000,0.375000,0.375000
50%,0.524555,0.444444,0.500000,0.428571,0.492476,0.393939,0.601015,0.500000,0.557070,0.343946,0.543451,0.556818,0.537162,0.522059
75%,0.658363,0.592593,0.625000,0.571429,0.610123,0.545455,0.739296,0.500000,0.750135,0.508588,0.625000,0.625000,0.625000,0.625000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [27]:
# Menentukan data inputan
X = df.drop(['CL','CD','CM25','CYAW','CROLL','CY'], axis = 1)
display(X)

           P0        Q0      V0       RHO        T0        RE      ALFA  BETA
0    0.689680  0.987654  0.6875  1.000000  0.000000  0.939394  0.002220   0.5
1    0.682562  0.962963  0.6250  1.000000  0.024624  0.909091  0.033619   0.5
2    0.674021  0.839506  0.3125  0.928571  0.051984  0.848485  0.065017   0.5
3    0.664057  0.888889  0.5625  0.928571  0.065663  0.878788  0.098319   0.5
4    0.658363  0.864198  0.4375  0.928571  0.073871  0.848485  0.131304   0.5
..        ...       ...     ...       ...       ...       ...       ...   ...
576  0.654093  0.592593  0.2500  0.714286  0.325581  0.575758  0.813828   0.5
577  0.661210  0.617284  0.3750  0.714286  0.328317  0.606061  0.845227   0.5
578  0.669751  0.765432  0.8125  0.642857  0.336525  0.636364  0.875040   0.5
579  0.686833  0.617284  0.4375  0.642857  0.344733  0.575758  0.904535   0.5
580  0.674021  1.000000  1.0000  0.642857  0.336525  1.000000  0.937203   0.5

[581 rows x 8 columns]

In [28]:
# Menentukan data output atau target
y = df.drop(columns=['P0','Q0','T0','RHO','V0','ALFA','BETA', 'RE'])
display(y)

           CL        CD  CM25      CYAW     CROLL        CY
0    0.016696  0.694596   1.0  0.000000  0.584459  0.930882
1    0.015495  0.629661   1.0  0.000000  0.672297  0.963235
2    0.013631  0.540427   1.0  0.306818  0.516892  0.630882
3    0.029871  0.444491   1.0  0.147727  0.692568  0.819118
4    0.061275  0.358609   1.0  0.375000  0.523649  0.598529
..        ...       ...   ...       ...       ...       ...
576  0.940713  0.788018   0.0  0.625000  0.415541  0.310294
577  0.952397  0.837453   0.0  0.534091  0.429054  0.327941
578  0.913494  0.949309   0.0  0.102273  0.000000  0.127941
579  0.883167  1.000000   0.0  0.647727  0.300676  0.336765
580  0.890583  1.000000   0.0  0.602273  0.287162  0.342647

[581 rows x 6 columns]

## Test dengan 8 Feature

In [35]:
#Membagi data menjadi data training dan tes  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=None, shuffle=False)
print("X_train {}, X_test {}, y_train {}, y_test {}" .format(X_train.shape, X_test.shape, y_train.shape, y_test.shape))

X_train (575, 8), X_test (6, 8), y_train (575, 6), y_test (6, 6)

In [30]:
# Random Forest Modeling Regressor
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.134
Mean Squared Error: 0.029
Root Mean Squared Error: 0.169

In [31]:
# Decission Tree Test
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.07
Mean Squared Error: 0.013
Root Mean Squared Error: 0.113

In [36]:
# Linear Regression Test
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.213
Mean Squared Error: 0.079
Root Mean Squared Error: 0.282

# Test dengan 4 Feature

In [37]:
# Menentukan data inputan
X = df.drop(['CL','CD','CM25','CYAW','CROLL','CY', 'Q0', 'RHO','V0','RE'], axis = 1)
display(X)

           P0        T0      ALFA  BETA
0    0.689680  0.000000  0.002220   0.5
1    0.682562  0.024624  0.033619   0.5
2    0.674021  0.051984  0.065017   0.5
3    0.664057  0.065663  0.098319   0.5
4    0.658363  0.073871  0.131304   0.5
..        ...       ...       ...   ...
576  0.654093  0.325581  0.813828   0.5
577  0.661210  0.328317  0.845227   0.5
578  0.669751  0.336525  0.875040   0.5
579  0.686833  0.344733  0.904535   0.5
580  0.674021  0.336525  0.937203   0.5

[581 rows x 4 columns]

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=None, shuffle=False)
print("X_train {}, X_test {}, y_train {}, y_test {}" .format(X_train.shape, X_test.shape, y_train.shape, y_test.shape))

X_train (575, 4), X_test (6, 4), y_train (575, 6), y_test (6, 6)

In [40]:
# Random Forest Modeling Regressor
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.134
Mean Squared Error: 0.027
Root Mean Squared Error: 0.164

In [41]:
# Decission Tree Test
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.092
Mean Squared Error: 0.024
Root Mean Squared Error: 0.154

In [42]:
# Linear Regression Test
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.192
Mean Squared Error: 0.06
Root Mean Squared Error: 0.246

# 2 feature

In [43]:
# Menentukan data inputan
X = df.drop(['CL','CD','CM25','CYAW','CROLL','CY', 'Q0', 'RHO','V0','RE', 'P0', 'T0'], axis = 1)
display(X)

         ALFA  BETA
0    0.002220   0.5
1    0.033619   0.5
2    0.065017   0.5
3    0.098319   0.5
4    0.131304   0.5
..        ...   ...
576  0.813828   0.5
577  0.845227   0.5
578  0.875040   0.5
579  0.904535   0.5
580  0.937203   0.5

[581 rows x 2 columns]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=None, shuffle=False)
print("X_train {}, X_test {}, y_train {}, y_test {}" .format(X_train.shape, X_test.shape, y_train.shape, y_test.shape))

X_train (575, 2), X_test (6, 2), y_train (575, 6), y_test (6, 6)

In [45]:
# Random Forest Modeling Regressor
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.069
Mean Squared Error: 0.01
Root Mean Squared Error: 0.102

In [46]:
# Decission Tree Test
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.079
Mean Squared Error: 0.02
Root Mean Squared Error: 0.14

In [47]:
# Linear Regression Test
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', np.round(metrics.mean_absolute_error(y_test, y_pred),3))
print('Mean Squared Error:', np.round(metrics.mean_squared_error(y_test, y_pred),3))
print('Root Mean Squared Error:', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))

Mean Absolute Error: 0.203
Mean Squared Error: 0.062
Root Mean Squared Error: 0.249